name: snake
channels:
  - defaults
dependencies:
  - python=3.7
  - pip:
    - appnope==0.1.2
    - backcall==0.2.0
    - cycler==0.10.0
    - decorator==4.4.2
    - ipython==7.21.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - numpy==1.20.1
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prompt-toolkit==3.0.16
    - ptyprocess==0.7.0
    - pygame==2.0.1
    - pygments==2.8.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - six==1.15.0
    - torch==1.7.1
    - torchvision==0.8.2
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
